<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use  AppBundle\Entity\Produit;



class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
public function getAllCategories(){

          

          //Methode 2 : Query Builder: (php)
          $em= $this-> getEntityManager();
          $query = $em ->createQueryBuilder();
          $query 
          -> select('p.categorie')
          -> distinct(true)
          -> from(produit::class,'p') //par ce qu'il manipule des entié 'le p est un alias'
          -> orderBy('p.categorie','ASC');
          //SELECT DISTINCT(categorie) FROM produit ORDER BY categorie ASC
          
        return $query -> getQuery() -> getResult();
}

public function getAllCategories2(){

     $em= $this-> getEntityManager();

    //Methode 1 : Create Query:(sql)
    
        $query = $em -> createQuery("SELECT DISTINCT(p.categorie) FROM AppBundle\Entity\Produit p ORDER BY p.categorie ASC");//car il ne manipule pas de table

        return $query -> getResult();//equivalent du FETCH::ASSOC
    }







}
